language: bash

sudo: false

services:
  - docker

before_script:
  - make image no-cache=yes tag=test
  - docker pull php:alpine

script:
  - make test tag=test

notifications:
  email:
    on_success: never
    on_failure: always
